### ISSUE TITLE
Bump removes versionName identifier from build.gradle

### ISSUE THREAD

**Issue by AlphaGit** [Grohden/react-native-cli-bump-version#2]
Hi! First of all, thanks for this wonderful tool -- it really comes in handy!

I've noticed that after running a version bump, the `versionName` identifier is removed from the build.gradle file.

Say that these are my initial build.gradle contents:

```gradle
    defaultConfig {
        applicationId "com.my.project"
        minSdkVersion rootProject.ext.minSdkVersion
        targetSdkVersion rootProject.ext.targetSdkVersion
        versionCode 3
        versionName "0.3.0"
    }
```

I will run:

```console
> λ npx react-native bump-version --type minor

iOS project.pbxproj code: 3 -> 4
Android build.gradle code: 3 -> 4
iOS project.pbxproj version: undefined -> 0.4.0
Android gradle.build version: "0.3.0" -> 0.4.0
package.json: 0.3.0 -> 0.4.0
```

This is the final build.gradle:

```gradle
    defaultConfig {
        applicationId "com.my.project"
        minSdkVersion rootProject.ext.minSdkVersion
        targetSdkVersion rootProject.ext.targetSdkVersion
        versionCode 4
        "0.4.0"
    }
```

Which in turns, makes the script fail on the next try, because it doesn't find the `versionName` identifier:

```console
> λ npx react-native bump-version --type minor

iOS project.pbxproj code: 4 -> 5
Android build.gradle code: 4 -> 5
iOS project.pbxproj version: undefined -> 0.5.0
error Cannot read property 'replace' of undefined. Run CLI with --verbose flag for more details.
TypeError: Cannot read property 'replace' of undefined
    at BuildGradleManager.setVersionName (C:\MyProject\node_modules\react-native-cli-bump-version\lib\index.js:92:17)
    at ProjectFilesManager.syncSemver (C:\MyProject\node_modules\react-native-cli-bump-version\lib\index.js:139:83)
    at ProjectFilesManager.exec (C:\MyProject\node_modules\react-native-cli-bump-version\lib\index.js:167:18)
    at exports.versioner (C:\MyProject\node_modules\react-native-cli-bump-version\lib\index.js:176:38)
    at Object.func (C:\MyProject\node_modules\react-native-cli-bump-version\react-native.config.js:21:13)
    at Command.handleAction (C:\MyProject\node_modules\@react-native-community\cli\build\index.js:186:23)
    at Command.listener (C:\MyProject\node_modules\@react-native-community\cli\node_modules\commander\index.js:315:8)
    at Command.emit (events.js:200:13)
    at Command.parseArgs (C:\MyProject\node_modules\@react-native-community\cli\node_modules\commander\index.js:651:12)
    at Command.parse (C:\MyProject\node_modules\@react-native-community\cli\node_modules\commander\index.js:474:21)
```

I think this might simply be a wrong replacement in the regex. (If there is a chance, I might come back myself with a PR for this issue.)

Thanks again!

**Comment by Grohden** [comment]
@AlphaGit thx for opening this issue

I'm gonna take a look into that as soon as I can!

**Comment by Grohden** [comment]
Oh, I think that I just have missed the `versionName` in the replace

https://github.com/Grohden/react-native-cli-bump-version/blob/49ad9ab97caec8e5257269bdddd2b80f4e44074e/src/index.ts#L140-L145

Looking at the `versionCode` in comparison, I re-add it to the replace:
https://github.com/Grohden/react-native-cli-bump-version/blob/49ad9ab97caec8e5257269bdddd2b80f4e44074e/src/index.ts#L128

I'm using gradle to get version names directly from `package.json` so I've been always skipping semver for android..

Anyway, gonna fix that and also setup some tests

**Comment by Grohden** [comment]
Ops, wrongly closed

**Comment by Grohden** [comment]
@AlphaGit 1.0.3 released, can you confirm that it works?

**Comment by AlphaGit** [comment]
@Grohden I can confirm it's working perfectly. Thank you very much for such a quick turnaround!

**Comment by Grohden** [comment]
I'm gonna close it then, feel free to reopen if needed

**Comment by AlphaGit** [comment]
I'll close the ticket I opened since I was able to confirm. However, if you'd like to run some internal cleanup things and reopen it, please feel free to do so.

Again, thank you very much. <3
